from .base import *

DEBUG = False

APPLICATION_HOST = os.getenv("IMI_HOST")
APPLICATION_ORIGIN = f"https://{APPLICATION_HOST}"

# Application domain
ALLOWED_HOSTS = [APPLICATION_HOST]

# CSRF
CSRF_COOKIE_DOMAIN = APPLICATION_HOST
CSRF_TRUSTED_ORIGINS = [APPLICATION_ORIGIN]
CSRF_COOKIE_SECURE = True

# Session
SESSION_COOKIE_DOMAIN = APPLICATION_HOST
SESSION_COOKIE_SECURE = True
