trigger:
- master
- development

pool:
  vmImage: ubuntu-22.04

variables:
  DJANGO_SETTINGS_MODULE: dashboard.settings.test
  IMI_DB_NAME: dashboard
  IMI_DB_USER: root
  IMI_DB_PASS: root
  IMI_DB_HOST: localhost

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'

- script: |
    sudo systemctl start mysql.service
    mysql -u $(IMI_DB_USER) --password=$(IMI_DB_PASS) -h $(IMI_DB_HOST) -P 3306 -e "CREATE DATABASE $(IMI_DB_NAME)"
  displayName: Install Database

- bash: echo "##vso[task.setvariable variable=PIP_CACHE_DIR]$(pip cache dir)"
  displayName: Export pip cache dir

- task: Cache@2
  inputs:
    path: $(PIP_CACHE_DIR)
    key: '"pip" | "$(Agent.OS)" | requirements.txt'
    restoreKeys: '"pip" | "$(Agent.OS)"'
  displayName: Cache dependencies

- script: pip install -r requirements.txt
  displayName: Install dependencies

- script: black . --check
  displayName: Lint

- script: python manage.py test --shuffle $(date +%s) --parallel $(nproc) --no-input --no-color
  displayName: Run tests
